const roleNameMap = {
  "interpersonal_interpersonal": "社交橋樑者",
  "interpersonal_action": "團隊溝通者",
  "interpersonal_creativity": "靈感協作家",
  "interpersonal_habit": "穩定領航者",
  "interpersonal_awareness": "共感觀察家",
  "action_interpersonal": "推進行動者",
  "action_action": "積極實踐者",
  "action_creativity": "執行創意者",
  "action_habit": "堅持開拓者",
  "action_awareness": "行動洞察者",
  "creativity_interpersonal": "靈感連結者",
  "creativity_action": "創新導向者",
  "creativity_creativity": "靈感開發者",
  "creativity_habit": "靈感行動派",
  "creativity_awareness": "靈感覺察者",
  "habit_interpersonal": "穩健合作家",
  "habit_action": "節奏掌握者",
  "habit_creativity": "穩定創造者",
  "habit_habit": "穩健執行者",
  "habit_awareness": "穩定觀察者",
  "awareness_interpersonal": "洞察觀察者",
  "awareness_action": "反思實踐者",
  "awareness_creativity": "深度靈感者",
  "awareness_habit": "自我精進者",
  "awareness_awareness": "自我洞察家",
};

export default roleNameMap;